### ISSUE TITLE
NullPointerException when authenticating

### ISSUE THREAD

**Issue by haphut** [P2Pvalue/incubator-wave#4]
With the incubator-wave server running at `http://localhost:9898`, I created a user named "user". As I tried to sign in with it, I got an HTTP response with status code 500. The server log contained this:
```
[java] INFO: Authenticated user user@local.net
[java] 68681 [qtp772489482-32] WARN org.eclipse.jetty.servlet.ServletHandler - /auth/signin
[java] java.lang.NullPointerException
[java] 	at org.waveprotocol.box.server.rpc.AuthenticationServlet.checkNoRedirect(AuthenticationServlet.java:432)
[java] 	at org.waveprotocol.box.server.rpc.AuthenticationServlet.doPost(AuthenticationServlet.java:256)
[java] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
[java] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
[java] 	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
[java] 	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
[java] 	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
[java] 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
[java] 	at org.waveprotocol.box.server.stat.RequestScopeFilter.doFilter(RequestScopeFilter.java:81)
[java] 	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
[java] 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
[java] 	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
[java] 	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
[java] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1615)
[java] 	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:248)
[java] 	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:211)
[java] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1615)
[java] 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
[java] 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
[java] 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:568)
[java] 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
[java] 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1110)
[java] 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:479)
[java] 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
[java] 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1044)
[java] 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
[java] 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
[java] 	at org.eclipse.jetty.server.Server.handle(Server.java:459)
[java] 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:281)
[java] 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:232)
[java] 	at org.eclipse.jetty.io.AbstractConnection$1.run(AbstractConnection.java:505)
[java] 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
[java] 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
[java] 	at java.lang.Thread.run(Thread.java:745)
[java] Feb 18, 2015 12:36:32 PM org.waveprotocol.box.server.rpc.AuthenticationServlet doPost
[java] INFO: User authentication failed: Login Failure: all modules ignored
```

**Comment by haphut** [comment]
Thanks!
